### ISSUE TITLE
Hello author, this project is a great job, please ask when the weights file in your project can be uploaded so that I can run through the code to learn

### ISSUE THREAD

**Issue by LooperzZ** [vishalsharbidar/SphereGlue#1]

**Comment by LooperzZ** [comment]
Hello author, this project is a great job, please ask when the weights file in your project can be uploaded so that I can run through the code to learn

**Comment by vishalsharbidar** [comment]
Hello LooperzZ, thanks for your patience. The weights can be found in the model_weights folder.
