### ISSUE TITLE
how to get Superpoint sphere coordinate

### ISSUE THREAD

**Issue by Lzf-Peter** [vishalsharbidar/SphereGlue#3]
Hi
I try to extract the superpoint keypoint with my own datasets, but the match result is not right. 
how to get the superpoint keypoint like the npz in the project?
your keypoint is like this:
![image](https://github.com/vishalsharbidar/SphereGlue/assets/30522679/629fde42-62c5-402c-bdb3-5cf5cde30956)
but my keypoint is like this:
![image](https://github.com/vishalsharbidar/SphereGlue/assets/30522679/1d7e914d-646a-46e7-9f18-91011b0cddc6)

**Comment by vishalsharbidar** [comment]
Hello Peter. I believe, your keypoints are in pixel coordinates. This has to be converted to spherical coordinates. 
Shortly, I will attach the code for this conversion.

**Comment by vishalsharbidar** [comment]
Hello Lzf-Peter, 
You can use this code to convert the keypoints from pixel to spherical coordinate.

def PixelToSpherical(pixel_coordinates:np.array, imgWidth:int, imgHeight:int):
    x,y = np.hsplit(pixel_coordinates,2)
    theta = (1. - (x + .5) / imgWidth) * 2*np.pi
    phi = ((y + .5) * np.pi) / imgHeight
    return np.hstack((phi, theta))

**Comment by vishalsharbidar** [comment]
Hello Lzf-Peter, 

For conversion of keypoints from pixel to spherical coordinates, please use the function PixelToSpherical. You can see this in the readme section. Thanks for your question.

**Comment by Lzf-Peter** [comment]
Thank you for your reply. I have solved this problem.
