### ISSUE TITLE
Curious about this work

### ISSUE THREAD

**Issue by TwiceMao** [vishalsharbidar/SphereGlue#4]
I am very curious about this work, will you continue to submit to CVPR/ICCV/ECCV or others after the improvement? This time, why not directly vote for the CVPR main meeting but the CVPR workshop?

**Comment by TwiceMao** [comment]
@vishalsharbidar

**Comment by vishalsharbidar** [comment]
Hello @TwiceMao, As of now it's under discussion. Thank you so much for your question.
